[[package]]
name = "dataclasses"
version = "0.8"
description = "A backport of the dataclasses module for Python 3.6"
optional = false
python-versions = ">=3.6, <3.7"

[[package]]
name = "importlib-metadata"
version = "4.8.1"
description = "Read metadata from Python packages"
optional = false
python-versions = ">=3.6"

[package.dependencies]
typing-extensions = {version = ">=3.6.4", markers = "python_version < \"3.8\""}
zipp = ">=0.5"

[package.extras]
docs = [ "sphinx",  "jaraco.packaging (>=8.2)",  "rst.linker (>=1.9)"]
perf = [ "ipython"]
testing = [ "pytest (>=4.6)",  "pytest-checkdocs (>=2.4)",  "pytest-flake8",  "pytest-cov",  "pytest-enabler (>=1.0.1)",  "packaging",  "pep517",  "pyfakefs",  "flufl.flake8",  "pytest-perf (>=0.9.2)",  "pytest-black (>=0.3.7)",  "pytest-mypy",  "importlib-resources (>=1.3)"]

[[package]]
name = "typing-extensions"
version = "3.10.0.2"
description = "Backported and Experimental Type Hints for Python 3.5+"
optional = false
python-versions = "*"

[[package]]
name = "zipp"
version = "3.6.0"
description = "Backport of pathlib-compatible object wrapper for zip files"
optional = false
python-versions = ">=3.6"

[package.extras]
docs = [ "sphinx",  "jaraco.packaging (>=8.2)",  "rst.linker (>=1.9)"]
testing = [ "pytest (>=4.6)",  "pytest-checkdocs (>=2.4)",  "pytest-flake8",  "pytest-cov",  "pytest-enabler (>=1.0.1)",  "jaraco.itertools",  "func-timeout",  "pytest-black (>=0.3.7)",  "pytest-mypy"]

[metadata]
lock-version = "1.1"
python-versions = "^3.6"
content-hash = "26a94cf2c7d15036a53f37261b22dac8c827cf925b83840f4e5edf6201eac1ba"

[[metadata.files.dataclasses]]
file = "dataclasses-0.8-py3-none-any.whl"
hash = "sha256:0201d89fa866f68c8ebd9d08ee6ff50c0b255f8ec63a71c16fda7af82bb887bf"

[[metadata.files.dataclasses]]
file = "dataclasses-0.8.tar.gz"
hash = "sha256:8479067f342acf957dc82ec415d355ab5edb7e7646b90dc6e2fd1d96ad084c97"

[[metadata.files.importlib-metadata]]
file = "importlib_metadata-4.8.1-py3-none-any.whl"
hash = "sha256:b618b6d2d5ffa2f16add5697cf57a46c76a56229b0ed1c438322e4e95645bd15"

[[metadata.files.importlib-metadata]]
file = "importlib_metadata-4.8.1.tar.gz"
hash = "sha256:f284b3e11256ad1e5d03ab86bb2ccd6f5339688ff17a4d797a0fe7df326f23b1"

[[metadata.files.typing-extensions]]
file = "typing_extensions-3.10.0.2-py2-none-any.whl"
hash = "sha256:d8226d10bc02a29bcc81df19a26e56a9647f8b0a6d4a83924139f4a8b01f17b7"

[[metadata.files.typing-extensions]]
file = "typing_extensions-3.10.0.2-py3-none-any.whl"
hash = "sha256:f1d25edafde516b146ecd0613dabcc61409817af4766fbbcfb8d1ad4ec441a34"

[[metadata.files.typing-extensions]]
file = "typing_extensions-3.10.0.2.tar.gz"
hash = "sha256:49f75d16ff11f1cd258e1b988ccff82a3ca5570217d7ad8c5f48205dd99a677e"

[[metadata.files.zipp]]
file = "zipp-3.6.0-py3-none-any.whl"
hash = "sha256:9fe5ea21568a0a70e50f273397638d39b03353731e6cbbb3fd8502a33fec40bc"

[[metadata.files.zipp]]
file = "zipp-3.6.0.tar.gz"
hash = "sha256:71c644c5369f4a6e07636f0aa966270449561fcea2e3d6747b8d23efaa9d7832"